### ISSUE TITLE
Where is .clang-format file?

### ISSUE THREAD

**Issue by RishabhRD** [salesforce/p4-fusion#3]
.clang-format file makes it easy to have a unified formatting throughout project.

**Comment by twarit-waikar** [comment]
There is a clang-format rules file present here: https://github.com/salesforce/p4-fusion/blob/master/p4-fusion/.clang-format

It is not present at the top level of the repository because it seemed cleaner than adding it to the top and retroactively disabling clang-format under the `vendor/` directory by adding another `.clang-format` file under vendor/ in addition to the top-level file.
